# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gostat < Formula
  desc "An interactive cli tool that easily binds HTTPS certificates and diagnoses whether certificates are applied with edge servers as proxy."
  homepage ""
  version "1.1.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ghdwlsgur/gostat/releases/download/v1.1.2/gostat_1.1.2_Darwin_arm64.tar.gz"
      sha256 "f41646135205399b36c32dfcf52946226f9812bab47e52297477edfcd02fa78b"

      def install
        bin.install "gostat"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ghdwlsgur/gostat/releases/download/v1.1.2/gostat_1.1.2_Darwin_x86_64.tar.gz"
      sha256 "28dc93cd66a84504eff1cdd1662993d1fd1eed7f2c4e15800a7d31b0e72c98f9"

      def install
        bin.install "gostat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ghdwlsgur/gostat/releases/download/v1.1.2/gostat_1.1.2_Linux_arm64.tar.gz"
      sha256 "263fbad89055c2f03734c8a1438c2a6227f964a773ad2c0ba47470fe041a0408"

      def install
        bin.install "gostat"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ghdwlsgur/gostat/releases/download/v1.1.2/gostat_1.1.2_Linux_x86_64.tar.gz"
      sha256 "938e350b83a85211bf332ba42ba4a4b7f575da8b54ed07accb31682a946879a2"

      def install
        bin.install "gostat"
      end
    end
  end
end
