# This file was generated by GoReleaser. DO NOT EDIT.
cask "gostat" do
  postflight_steps do
    run "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "{{staged_path}}/gostat"],
        must_succeed: false
  end

  version "1.3.1"

  on_macos do
    on_intel do
      sha256 "4bb7347a7b8829f0c923c4546c433e4b7636f2fe8729c753fa041ee90ca41c62"
      url "https://github.com/ghdwlsgur/gostat/releases/download/v#{version}/gostat_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a08571eb7ae39a83782133f0be05c9d4962574f6aababc79aaf2169ac5b672df"
      url "https://github.com/ghdwlsgur/gostat/releases/download/v#{version}/gostat_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8e2a46220fa243888675a327961e57710f27263fe442e13a7e22a08386669946"
      url "https://github.com/ghdwlsgur/gostat/releases/download/v#{version}/gostat_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ea7db5f3bfe623ad6f9eea663a81e79a2a2d55226b6a84b9b36a08645ee82ab6"
      url "https://github.com/ghdwlsgur/gostat/releases/download/v#{version}/gostat_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "gostat"
  desc "HTTP GET to a domain's A records or a pinned edge IP, with response headers and per-stage latency"
  homepage "https://github.com/ghdwlsgur/gostat"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gostat"

  # No zap stanza required

end
