# This file was generated by GoReleaser. DO NOT EDIT.
cask "gostat" do
  postflight_steps do
    run "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "{{staged_path}}/gostat"],
        must_succeed: false
  end

  version "1.3.10"

  on_macos do
    on_arm do
      sha256 "da446c4f67add2d8aaf9b02871d41deac8e053076d14bbd88933f1ab1acc4289"
      url "https://github.com/ghdwlsgur/gostat/releases/download/v#{version}/gostat_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8d14a1d0724076a9581a6744e24c7306d0a040d2422be9c2621de6773f69d27f"
      url "https://github.com/ghdwlsgur/gostat/releases/download/v#{version}/gostat_#{version}_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3f4676ee68681a25eb0216cc6db8011bb067b3c26a1ac911c2763a4eb5a6fca9"
      url "https://github.com/ghdwlsgur/gostat/releases/download/v#{version}/gostat_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "99f1b3428d3a917d1dd8d673d2845a92e019c458c84a77b83bb98da728e30041"
      url "https://github.com/ghdwlsgur/gostat/releases/download/v#{version}/gostat_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "gostat"
  desc "Send an HTTP GET request to a domain's A record or a pinned edge IP, and measure the response headers and latency at each stage"
  homepage "https://github.com/ghdwlsgur/gostat"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gostat"

  # No zap stanza required
end
