# This file was generated by GoReleaser. DO NOT EDIT.
cask "gostat" do
  postflight_steps do
    run "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "{{staged_path}}/gostat"],
        must_succeed: false
  end

  version "1.3.5"

  on_macos do
    on_arm do
      sha256 "a4172c9fa43570898a476d4a8f59b08eb9de1484bebbd69d665f2372a5e84316"
      url "https://github.com/ghdwlsgur/gostat/releases/download/v#{version}/gostat_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4b26e42f10ea4fe2042f4efda18a0a69de897fe175ca36a692675e67fa8fb2e4"
      url "https://github.com/ghdwlsgur/gostat/releases/download/v#{version}/gostat_#{version}_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "25c6f0260b079d21f9ac72e5478f21191ed70227bfcedc5ee678c4726add061a"
      url "https://github.com/ghdwlsgur/gostat/releases/download/v#{version}/gostat_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e815c27415520d60be4b1650c43604aeb1fe0d9df9f5aea4e074e232bb274044"
      url "https://github.com/ghdwlsgur/gostat/releases/download/v#{version}/gostat_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "gostat"
  desc "Send an HTTP GET request to a domain's A record or a pinned edge IP, and measure the response headers and latency at each stage"
  homepage "https://github.com/ghdwlsgur/gostat"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gostat"

  # No zap stanza required
end
